const actionTypes = {
    //User
    LOGGIN_SUCCESS: 'LOGGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    // AUTH_REQUEST: 'AUTH_REQUEST',

    //Crud
    ITEM_CREATED: 'ITEM_CREATED',
    // ITEM_EDITED: 'ITEM_EDITED',
    // ITEM_DELETED: 'ITEM_DELETED',
    // ITEM_FETCHED_ONE: 'ITEM_FETCHED_ONE',
    // ITEM_FETCHED_ALL: 'ITEM_FETCHED_ALL',
    // ITEM_FETCHED_BY_ID: 'ITEM_FETCHED_BY_ID',

    // PENDING: 'PENDING',
    REMOTE_ERROR: 'REMOTE_ERROR',
}

export default actionTypes;